# Generated by Django 2.0.13 on 2020-05-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200505_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=100, verbose_name='사용자 이메일'),
            preserve_default=False,
        ),
    ]
